#!/bin/bash
#PBS -N cpg_covg
#PBS -e QQQ.stderr
#PBS -o QQQ.stdout
#PBS -l nodes=1:ppn=10,mem=220gb,walltime=72:00:00

set -euo pipefail

DIRLOC=2019_11_07_FallopianTube_WGBS_Kit_Comparison

cd ${DIRLOC}/analysis

bash ${DIRLOC}/analysis/cpg_counter.sh \
    -o ${DIRLOC}/analysis/cpg_covg \
    ${DIRLOC}/qc_assets/hg38 \
    QQQ \
    ${DIRLOC}/analysis/align/QQQ.sorted.markdup.bam
