#!/bin/bash
#PBS -N kit_comp
#PBS -e QQQ.stderr
#PBS -o QQQ.stdout
#PBS -l nodes=1:ppn=20,mem=220gb,walltime=72:00:00

set -euo pipefail

echo "Started at `date`"

# Useful paths
BISCUIT="installed_packages/biscuit-release-0.3.16.20200420"
SAMBLST="installed_packages/samblaster-v.0.1.25"
DIRLOC="2019_11_07_FallopianTube_WGBS_Kit_Comparison/analysis/align"
REFLOC="references/biscuit_gencode_rel32_p13_all"
FASTQS="2019_11_07_FallopianTube_WGBS_Kit_Comparison/trimmed_fastq"
ASSETS="installed_packages/biscuit-release-0.3.16.20200420/hg38"

# Use the same number of threads throughout
NTHREADS=20

# Change to working directory
cd ${DIRLOC}

# Print out versions of software used
echo "Using versions:"
echo -e "\tsamtools: `samtools --version`"
echo -e "\tsamblaster: `${SAMBLST}/samblaster --version`"
echo -e "\tbedtools: `bedtools --version`"
echo -e "\tbgzip: `bgzip --version`"
echo -e "\ttabix: `tabix --version`"

# biscuit align
${BISCUIT}/biscuit align -M -t "${NTHREADS}" \
    -R '@RG\tLB:QQQ\tID:WGMS_Kit_Comp_QQQ\tPL:Illumina\tPU:NovaSeq\tSM:QQQ' \
    ${REFLOC}/GRCh38.p13.genome.fa \
    ${FASTQS}/QQQ_L000_R1_001_val_1.fq.gz \
    ${FASTQS}/QQQ_L000_R2_001_val_2.fq.gz | \
${SAMBLST}/samblaster -M | \
samtools view -hbu | \
samtools sort -@ "${NTHREADS}" -m 5G -o QQQ.sorted.markdup.bam -O BAM -
samtools index -@ "${NTHREADS}" QQQ.sorted.markdup.bam

# biscuit pileup
${BISCUIT}/biscuit pileup -q "${NTHREADS}" \
    ${REFLOC}/GRCh38.p13.genome.fa \
    QQQ.sorted.markdup.bam | \
bgzip > QQQ.pileup.vcf.gz
tabix -p vcf QQQ.pileup.vcf.gz

# biscuit cg vcf2bed
${BISCUIT}/biscuit vcf2bed -t cg \
    QQQ.pileup.vcf.gz | \
bedtools sort -i - | \
${BISCUIT}/biscuit mergecg \
    ${REFLOC}/GRCh38.p13.genome.fa - | \
bgzip > QQQ.cg.sorted.mergecg.bed.gz
tabix -p bed QQQ.cg.sorted.mergecg.bed.gz

# biscuit c context vcf2bed
${BISCUIT}/biscuit vcf2bed -t c -e \
    QQQ.pileup.vcf.gz | \
gzip > QQQ.c.context.sorted.bed.gz

# Launch qc
${BISCUIT}/scripts/QC.sh \
    -v QQQ.pileup.vcf.gz \
    -o QQQ_QC \
    ${ASSETS} \
    ${REFLOC}/GRCh38.p13.genome.fa \
    QQQ \
    QQQ.sorted.markdup.bam

samtools flagstat -@ "${NTHREADS}" \
    QQQ.sorted.markdup.bam \
    > QQQ.sorted.markdup.bam.flagstat

samtools stats -@ "${NTHREADS}" \
    QQQ.sorted.markdup.bam \
    > QQQ.sorted.markdup.bam.stat

echo "Ended at `date`"
